apiVersion: v1
kind: Service
metadata:
  name: firstapp
  namespace: namespace-workflow-1720085592705
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: firstapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080